---
abstract: 'Redis Cluster client for Perl'
author:
  - 'SMS Online <dev.opensource@sms-online.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Path: '0'
  Pod::Coverage: '0.18'
  Test::EOL: '0'
  Test::Exception: '0'
  Test::Fixme: '0'
  Test::Kwalitee: '0'
  Test::More: '0'
  Test::Perl::Critic: '0'
  Test::Pod: '1.22'
  Test::Pod::Coverage: '1.08'
  Test::Strict: '0'
configure_requires:
  ExtUtils::MakeMaker: 6.63_03
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.150001'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: redis-cluster-perl
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Data::Dumper: '0'
  Digest::CRC: '0.18'
  List::MoreUtils: '0.22'
  Params::Validate: '0'
  Redis: '1.979'
  Try::Tiny: '0'
  perl: '5.008'
version: '0.02'
